### ISSUE TITLE
No Module named 'UBX_PROTOCOL'

### ISSUE THREAD

**Issue by abishur** [melopero/Melopero_SAM-M8Q#1]
While trying to follow your example, I'm getting errors saying there is no module named ubx_protocol and that module can't be found to install with pip3.  Where is the module you use for this?

**Comment by leoli51** [comment]
Hi, the example in the readme used old module names. Now the names should be the right ones. You can have a look at the examples in the example directory. The module is called [melopero_ubx](https://pypi.org/project/melopero-ubx/) . Thank you very much for pointing this out.
